# Generated by Django 2.0.7 on 2018-12-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_favoriteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
    ]
